params:
  epochs: 1
  batch_size: 32
  no_classes: 10
  input_shape: [28,28]
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: optimizer7
  optimizer1: SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
  optimizer2: SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=False)
  optimizer3: RMSprop
  optimizer4: Adagrad
  optimizer5: Adadelta
  optimizer6: Adamax
  optimizer7: Adam
  
 
  validation_datasize: 5000



artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dir: plots
  checkoint_dir: checkpoints
  model_name: model.h5
  plots_name: plot.png

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs
  tf_logs_name: tf_logs