params:
  epochs: 30
  batch_size: 32
  no_classes: 10
  input_shape: [28,28]
  loss_functions: stochastic gradient descent
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000



artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dir: plots
  checkoint_dir: checkpoints

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs 